const config = {
  COGNITO_DOMAIN: "YOUR_COGNITO_DOMAIN",
  COGNITO_CLIENT_ID: "YOUR_COGNITO_CLIENT_ID",
  LOGOUT_URI: "YOUR_LOGOUT_URI",
  REDIRECT_URI: "YOUR_REDIRECT_URI",
  API_ENDPOINT: "YOUR)API_ENDPOINT",
  redirect_uri: "YOUR_REDIRECT_URI",
  USERPOOLID: "YOUR_USERPOOLID",
};
export default config;
